### ISSUE TITLE
example yaml file doesnt works

### ISSUE THREAD

**Issue by UserNameGGarri** [MIT-SPARK/Kimera-Multi#16]
0: frontend
![image](https://github.com/MIT-SPARK/Kimera-Multi/assets/114667421/f8774aa2-c298-4f5d-99a3-80eae50012fd)

1: dpgo-
![image](https://github.com/MIT-SPARK/Kimera-Multi/assets/114667421/fa613205-f71d-446b-b80b-f64beddec7d6)

2: vio
![image](https://github.com/MIT-SPARK/Kimera-Multi/assets/114667421/82a9d2f9-570b-4145-8453-7933c744cf33)
![image](https://github.com/MIT-SPARK/Kimera-Multi/assets/114667421/af1e59c8-480a-4cea-8a4a-72ebfc9fd1f3)

3: data
![image](https://github.com/MIT-SPARK/Kimera-Multi/assets/114667421/dd19afef-6889-4ad7-a0a7-76fc3341de5f)

log files
![image](https://github.com/MIT-SPARK/Kimera-Multi/assets/114667421/56f95990-5262-494b-b9f1-7edc9a93f267)
![image](https://github.com/MIT-SPARK/Kimera-Multi/assets/114667421/275bcfee-9300-4fea-a103-c05bd5d487f4)

I'm working with rosbag files and have configured them using the '1014-example.yaml' file. While the rosbag files are functioning correctly, I'm encountering an issue where certain log files (e.g., acl_jackal-distributed_loop_closure-distributed_loop_closure_node-1*.log) are not being generated as expected. Is there an additional setting or option that needs to be adjusted for Kimera Multi to generate these log files properly?
I'm working in Docker(Ubuntu 20.04, ROS noetic, CUDA Version 12.2(Nvidia RTX 4090) )

**Comment by UserNameGGarri** [comment]
Problem has solved. However rosbag file works slowly while doing with cpu. Can kimera-multi run with cuda?

**Comment by yunzc** [comment]
Hi Thanks for your interest in our work and trying out Kimera-Multi.
Unfortunately Kimera-Multi only runs on CPU.
Regarding the rosbag files working slowly, could you try [decompressing](http://wiki.ros.org/rosbag/Commandline#rosbag_decompress) the bags with `rosbag decompress`? That might resolve your issues.

**Comment by UserNameGGarri** [comment]
@yunzc Do you have plans to integrate this project with CUDA? I was planning to make a map in realtime by using Kimera-multi.

**Comment by yunzc** [comment]
Hi @UserNameGGarri we don't have plans on integrating with Cuda. However, Kimera-Multi does work in real time even on CPU. We have tested this on Intel-NUCs on robots in several setups.

**Comment by UserNameGGarri** [comment]
@yunzc Thanks for replying and your works. I'll try rosbag decompress and I have another questions.
After launching 1014-example.yaml file I was only able to check each robots rosbag path, not the meshed path (without vision information(map)). Is there a topic that has meshed all the local path? or do i need to make it? Also as i saw on README.md image file, there was point clouds belong the path. Could i get the map like what i saw? Sorry for bothering

**Comment by yunzc** [comment]
Sorry not quite sure what you mean. So the rosbags consists of raw sensor data and the examples should get you up generating the robot trajectories (inherently it is using the vision information to do so).

If you mean the actual dense mesh, the current example does not do that (I did not include due to more complex set up and maintenance). See my response in https://github.com/MIT-SPARK/Kimera-Multi/issues/17 to set that up.

**Comment by UserNameGGarri** [comment]
Hello @yunzc . It seems you have correctly understood, and I have checked the content of issue #17 as you mentioned. The details I am looking to confirm are as follows:

1. I understand that each local path is generated through Kimera-VIO and then meshed via Kimera-Multi. If so, where can this meshed map be viewed? From what I've understood through issue #17, it seems like it can be checked through Kimera-Semantics. Is that correct?
2. Is the input file format for Kimera-VIO only in rosbag format, or is it also possible to receive data in real-time from an actual robot? (I plan to implement this on a drone as well.)

I am continuing to grasp the details by reading through papers and the code, but I still find it challenging to locate specific information. I apologize for the continuous questions.

**Comment by yunzc** [comment]
1. Since overall we are working in a ROS framework, you can visualize the mesh via rviz. The odometric mesh if published via Kimera-Semantics and the optimized globally consistent mesh is published by Kimera-PGMO.
2. When we play back the rosbag it essentially simulates data streaming in real time (the interface is the same, via ROS topics). So there shouldn't be changes needed to receive data in real time. (In fact, the rosbags that we have provided were recorded during our experiments, where we were doing real-time mapping on a team of jackal robots using the same launch files that we are calling in the example).

**Comment by UserNameGGarri** [comment]
thanks I'll try what you recommend.

**Comment by leefan96** [comment]
> Problem has solved. However rosbag file works slowly while doing with cpu. Can kimera-multi run with cuda?

i have the same problem ,can you tell me how to solve it, shanks

**Comment by UserNameGGarri** [comment]
@leefan96 
hello
i forgot how i solve that problem.
have you tried reindexing rosbag? reindexing was the one of the solution
