### ISSUE TITLE
Is it ok to use my own RGBD dataset?

### ISSUE THREAD

**Issue by TwiceMao** [MIT-SPARK/Kimera-Multi#4]
Thank you for such a great job！
Is it ok to use my own RGBD dataset? I have a mutli-room RGBD dataset, but I don't have IMU, LiDAR, Stereo and other data, can your code run on this dataset?
Besides, the RGB image of my RGBD dataset is in .jpg format, the Depth image is in .png format, and the pose is in .txt format. Will this still work with your work? If not, how can I convert the data format to meet the requirements?
Thank you for your reply！

**Comment by yuluntian** [comment]
Hi! Currently, Kimera-VIO requires IMU so the short answer is no. However, since the Kimera-Multi system design is modular, it is possible to switch Kimera-VIO with another visual odometry pipeline. 

Regarding dataset format, the most straightforward way is to convert your data into rosbags. Once that is done, you can test Kimera-Multi on your custom datasets in a way similar to our example: https://github.com/MIT-SPARK/Kimera-Multi#examples--usage
