### ISSUE TITLE
Error installing dependencies： ros-melodic-mesh-tools : Depends: ros-melodic-rviz-mesh-plugin but it is not installable E: Unable to correct problems, you have held broken packages.

### ISSUE THREAD

**Issue by NatureLan-sudo** [MIT-SPARK/Kimera-Multi#5]
@yuluntian Hello, sorry to bother you and thanks for the great work. I am using ubuntu18.04. When installing dependencies, the following error occurs. It seems that the package has been abandoned. How can I solve the dependency problem?
```
The following packages have unmet dependencies:
 ros-melodicmesh-tools : Depends: ros-melodic-rviz-mesh-plugin but it is not installable
E: Unable to correct problems, you have held broken packages.
```
When I use:
`sudo apt install ros-melodic-rviz-mesh-plugin`,
The following prompt will appear：
```
Reading package list... Done
Analyzing the dependency tree of the package
Reading status information... Done
Package ros-melodic-rviz-mesh-plugin is not available, but it is referenced by other packages.
This may mean that the missing package may be obsolete,
or can only be found in other release sources
E: Package ros-melodic-rviz-mesh-plugin has no installation candidates
```

**Comment by yuluntian** [comment]
@NatureLan-sudo This particular dependency (ros-melodic-mesh-tools) might not be needed, because it is also included as one of the packages in the catkin workspace (see this [line](https://github.com/MIT-SPARK/Kimera-Multi/blob/main/kimera_multi.repos#L90)) and built from source. 

Can you skip this dependency (comment out the corresponding line in dependencies.sh) for now and try to build the catkin workspace? We will update the dependencies if this works out.
